[2025-03-19T22:31:58.741+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T22:31:58.757+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2024-05-29T00:00:00+00:00 [queued]>
[2025-03-19T22:31:58.768+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2024-05-29T00:00:00+00:00 [queued]>
[2025-03-19T22:31:58.769+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-19T22:31:58.787+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task_1> on 2024-05-29 00:00:00+00:00
[2025-03-19T22:31:58.795+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2067) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T22:31:58.797+0000] {standard_task_runner.py:72} INFO - Started process 2075 to run task
[2025-03-19T22:31:58.797+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_and_backfill', 'task_1', 'scheduled__2024-05-29T00:00:00+00:00', '--job-id', '3521', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmp6zal89vt']
[2025-03-19T22:31:58.799+0000] {standard_task_runner.py:105} INFO - Job 3521: Subtask task_1
[2025-03-19T22:31:58.858+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2024-05-29T00:00:00+00:00 [running]> on host 63fd4b143e0a
[2025-03-19T22:31:58.920+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_catchup_and_backfill' AIRFLOW_CTX_TASK_ID='task_1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-29T00:00:00+00:00'
[2025-03-19T22:31:58.921+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T22:31:58.934+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T22:31:58.935+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo ']
[2025-03-19T22:31:58.942+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T22:31:58.946+0000] {subprocess.py:106} INFO - 
[2025-03-19T22:31:58.947+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-19T22:31:58.969+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T22:31:58.970+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_and_backfill, task_id=task_1, run_id=scheduled__2024-05-29T00:00:00+00:00, execution_date=20240529T000000, start_date=20250319T223158, end_date=20250319T223158
[2025-03-19T22:31:59.022+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T22:31:59.039+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T22:31:59.040+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
