[2025-03-19T22:31:19.245+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T22:31:19.275+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2024-04-03T00:00:00+00:00 [queued]>
[2025-03-19T22:31:19.299+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2024-04-03T00:00:00+00:00 [queued]>
[2025-03-19T22:31:19.300+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-19T22:31:19.414+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task_1> on 2024-04-03 00:00:00+00:00
[2025-03-19T22:31:19.438+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_and_backfill', 'task_1', 'scheduled__2024-04-03T00:00:00+00:00', '--job-id', '3465', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmp2j7zbpo6']
[2025-03-19T22:31:19.456+0000] {standard_task_runner.py:105} INFO - Job 3465: Subtask task_1
[2025-03-19T22:31:19.459+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1821) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T22:31:19.466+0000] {standard_task_runner.py:72} INFO - Started process 1826 to run task
[2025-03-19T22:31:19.656+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2024-04-03T00:00:00+00:00 [running]> on host 63fd4b143e0a
[2025-03-19T22:31:21.495+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_catchup_and_backfill' AIRFLOW_CTX_TASK_ID='task_1' AIRFLOW_CTX_EXECUTION_DATE='2024-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-03T00:00:00+00:00'
[2025-03-19T22:31:21.519+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T22:31:21.795+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T22:31:21.815+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo ']
[2025-03-19T22:31:21.912+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T22:31:21.919+0000] {subprocess.py:106} INFO - 
[2025-03-19T22:31:21.925+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-19T22:31:22.404+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T22:31:22.429+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_and_backfill, task_id=task_1, run_id=scheduled__2024-04-03T00:00:00+00:00, execution_date=20240403T000000, start_date=20250319T223119, end_date=20250319T223122
[2025-03-19T22:31:22.980+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T22:31:23.727+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T22:31:23.769+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
