[2025-03-19T22:33:31.601+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T22:33:31.648+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2025-01-31T00:00:00+00:00 [queued]>
[2025-03-19T22:33:31.668+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2025-01-31T00:00:00+00:00 [queued]>
[2025-03-19T22:33:31.670+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-19T22:33:31.701+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task_1> on 2025-01-31 00:00:00+00:00
[2025-03-19T22:33:31.739+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3123) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T22:33:31.745+0000] {standard_task_runner.py:72} INFO - Started process 3128 to run task
[2025-03-19T22:33:31.747+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_and_backfill', 'task_1', 'scheduled__2025-01-31T00:00:00+00:00', '--job-id', '3768', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmp0o152wbb']
[2025-03-19T22:33:31.757+0000] {standard_task_runner.py:105} INFO - Job 3768: Subtask task_1
[2025-03-19T22:33:32.036+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2025-01-31T00:00:00+00:00 [running]> on host 63fd4b143e0a
[2025-03-19T22:33:32.727+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_catchup_and_backfill' AIRFLOW_CTX_TASK_ID='task_1' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-31T00:00:00+00:00'
[2025-03-19T22:33:32.754+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T22:33:32.925+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T22:33:32.933+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo ']
[2025-03-19T22:33:33.013+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T22:33:33.100+0000] {subprocess.py:106} INFO - 
[2025-03-19T22:33:33.106+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-19T22:33:33.339+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T22:33:33.344+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_and_backfill, task_id=task_1, run_id=scheduled__2025-01-31T00:00:00+00:00, execution_date=20250131T000000, start_date=20250319T223331, end_date=20250319T223333
[2025-03-19T22:33:33.568+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T22:33:33.829+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T22:33:33.847+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
