[2025-03-19T19:11:55.770+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T19:11:55.968+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_Api_v2.get_name scheduled__2024-12-26T00:00:00+00:00 [queued]>
[2025-03-19T19:11:56.033+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_Api_v2.get_name scheduled__2024-12-26T00:00:00+00:00 [queued]>
[2025-03-19T19:11:56.040+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-19T19:11:56.234+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): get_name> on 2024-12-26 00:00:00+00:00
[2025-03-19T19:11:56.383+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10487) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T19:11:56.403+0000] {standard_task_runner.py:72} INFO - Started process 10512 to run task
[2025-03-19T19:11:56.384+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_Api_v2', 'get_name', 'scheduled__2024-12-26T00:00:00+00:00', '--job-id', '3019', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_taskflow_api.py', '--cfg-path', '/tmp/tmpvskyrlx3']
[2025-03-19T19:11:56.439+0000] {standard_task_runner.py:105} INFO - Job 3019: Subtask get_name
[2025-03-19T19:11:58.742+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_taskflow_Api_v2.get_name scheduled__2024-12-26T00:00:00+00:00 [running]> on host 63fd4b143e0a
[2025-03-19T19:12:07.794+0000] {job.py:229} INFO - Heartbeat recovered after 13.13 seconds
[2025-03-19T19:12:12.081+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_taskflow_Api_v2' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-26T00:00:00+00:00'
[2025-03-19T19:12:12.169+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T19:12:12.633+0000] {python.py:240} INFO - Done. Returned value was: {'first_name': 'John', 'last_name': 'Doe'}
[2025-03-19T19:22:05.589+0000] {job.py:229} INFO - Heartbeat recovered after 597.98 seconds
[2025-03-19T19:22:20.125+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T19:22:20.284+0000] {job.py:229} INFO - Heartbeat recovered after 14.79 seconds
[2025-03-19T19:22:20.999+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_taskflow_Api_v2, task_id=get_name, run_id=scheduled__2024-12-26T00:00:00+00:00, execution_date=20241226T000000, start_date=20250319T191155, end_date=20250319T192220
[2025-03-19T19:22:25.460+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T19:22:27.224+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-03-19T19:22:30.614+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-19T19:22:30.785+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
