[2025-03-19T19:11:18.641+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T19:11:19.601+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2025-03-19T19:11:20.640+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2025-03-19T19:11:20.660+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-19T19:11:20.848+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task_1> on 2023-10-01 00:00:00+00:00
[2025-03-19T19:11:21.078+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10276) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T19:11:21.091+0000] {standard_task_runner.py:72} INFO - Started process 10306 to run task
[2025-03-19T19:11:21.088+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_and_backfill', 'task_1', 'scheduled__2023-10-01T00:00:00+00:00', '--job-id', '2962', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpcfz8ohw7']
[2025-03-19T19:11:21.400+0000] {standard_task_runner.py:105} INFO - Job 2962: Subtask task_1
[2025-03-19T19:11:22.011+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2023-10-01T00:00:00+00:00 [running]> on host 63fd4b143e0a
[2025-03-19T19:11:24.069+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_catchup_and_backfill' AIRFLOW_CTX_TASK_ID='task_1' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-01T00:00:00+00:00'
[2025-03-19T19:11:24.120+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T19:11:24.888+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T19:11:25.008+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo ']
[2025-03-19T19:11:25.324+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T19:11:25.408+0000] {subprocess.py:106} INFO - 
[2025-03-19T19:11:25.485+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-19T19:11:26.334+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T19:11:26.351+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_and_backfill, task_id=task_1, run_id=scheduled__2023-10-01T00:00:00+00:00, execution_date=20231001T000000, start_date=20250319T191119, end_date=20250319T191126
[2025-03-19T19:11:27.313+0000] {job.py:229} INFO - Heartbeat recovered after 11.24 seconds
[2025-03-19T19:11:27.444+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T19:11:27.510+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T19:11:27.513+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
