[2025-03-19T22:31:47.993+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T22:31:48.055+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2025-03-19T22:31:48.076+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2025-03-19T22:31:48.078+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-19T22:31:48.121+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task_1> on 2024-04-28 00:00:00+00:00
[2025-03-19T22:31:48.154+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1932) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T22:31:48.143+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_and_backfill', 'task_1', 'scheduled__2024-04-28T00:00:00+00:00', '--job-id', '3490', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpgrsap48x']
[2025-03-19T22:31:48.158+0000] {standard_task_runner.py:72} INFO - Started process 1945 to run task
[2025-03-19T22:31:48.162+0000] {standard_task_runner.py:105} INFO - Job 3490: Subtask task_1
[2025-03-19T22:31:48.275+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2024-04-28T00:00:00+00:00 [running]> on host 63fd4b143e0a
[2025-03-19T22:31:48.392+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_catchup_and_backfill' AIRFLOW_CTX_TASK_ID='task_1' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-28T00:00:00+00:00'
[2025-03-19T22:31:48.393+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T22:31:48.422+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T22:31:48.423+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo ']
[2025-03-19T22:31:48.430+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T22:31:48.433+0000] {subprocess.py:106} INFO - 
[2025-03-19T22:31:48.434+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-19T22:31:48.462+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T22:31:48.463+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_and_backfill, task_id=task_1, run_id=scheduled__2024-04-28T00:00:00+00:00, execution_date=20240428T000000, start_date=20250319T223148, end_date=20250319T223148
[2025-03-19T22:31:48.524+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T22:31:48.549+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T22:31:48.550+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
