[2025-03-19T19:11:48.284+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T19:11:48.373+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2023-10-14T00:00:00+00:00 [queued]>
[2025-03-19T19:11:48.403+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2023-10-14T00:00:00+00:00 [queued]>
[2025-03-19T19:11:48.405+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-19T19:11:48.544+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task_1> on 2023-10-14 00:00:00+00:00
[2025-03-19T19:11:48.906+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_and_backfill', 'task_1', 'scheduled__2023-10-14T00:00:00+00:00', '--job-id', '3001', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpuok0mk3j']
[2025-03-19T19:11:48.919+0000] {standard_task_runner.py:105} INFO - Job 3001: Subtask task_1
[2025-03-19T19:11:48.942+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10429) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T19:11:48.948+0000] {standard_task_runner.py:72} INFO - Started process 10447 to run task
[2025-03-19T19:11:49.425+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_and_backfill.task_1 scheduled__2023-10-14T00:00:00+00:00 [running]> on host 63fd4b143e0a
[2025-03-19T19:11:49.859+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_catchup_and_backfill' AIRFLOW_CTX_TASK_ID='task_1' AIRFLOW_CTX_EXECUTION_DATE='2023-10-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-14T00:00:00+00:00'
[2025-03-19T19:11:49.876+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T19:11:49.953+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T19:11:49.971+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo ']
[2025-03-19T19:11:50.004+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T19:11:50.017+0000] {subprocess.py:106} INFO - 
[2025-03-19T19:11:50.020+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-19T19:11:50.091+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T19:11:50.093+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_and_backfill, task_id=task_1, run_id=scheduled__2023-10-14T00:00:00+00:00, execution_date=20231014T000000, start_date=20250319T191148, end_date=20250319T191150
[2025-03-19T19:11:50.221+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T19:11:50.361+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T19:11:50.370+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
